// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grkpwafluryksufqvmdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdya3B3YWZsdXJ5a3N1ZnF2bWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzUzNTMsImV4cCI6MjA2NTU1MTM1M30.5THaWkoAzKhwgsa5KHog_i2Lf9uCxHFlfYcBpTL9LWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);